version: '3'
services:
  app:
    container_name: alterra-mini-project
    build:
      context: .
    depends_on:
      db :
        condition: service_healthy
    networks:
      - backend
    ports:
      - 8080:8080
    hostname: app
  db:
    image: mysql:8.0
    container_name: db_mysql
    networks:
      - backend
    ports:
      - 8000:3306
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
    environment:
      - MYSQL_ROOT_HOST=localhost
      - MYSQL_ROOT_PASSWORD=rifkhi
      - MYSQL_DATABASE=LMS
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rifkhi
    hostname: db_mysql
networks:
  backend:
