name: docker-ec2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: SSH into AWS server
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-25-88-249.ap-southeast-2.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull Docker image on AWS server
        run: |
          ssh ubuntu@3.25.88.249 'docker pull go-application'

      - name: Run Docker container on AWS server
        run: |
          ssh ubuntu@3.25.88.249 'docker run -dp 8080:8080 go-application'
