name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2b

      - name: SSH into AWS server
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-25-88-249.ap-southeast-2.compute.amazonaws.com
          username: admin
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull Docker image on AWS server
        run: |
          ssh user@ec2-3-25-88-249.ap-southeast-2.compute.amazonaws.com 'docker pull your_image_name'

      - name: Run Docker container on AWS server
        run: |
          ssh user@ec2-3-25-88-249.ap-southeast-2.compute.amazonaws.com 'docker run -d -p 8080:80 your_image_name'
